Feat/11439 sample app has more queries
Trihydro/sdx-sample-app pull request #40
Opened 2024-06-07 21:16 UTC by mdorford

This is a replacement PR for my previous 11439 PR.

2024-10-22 19:39 UTC, pmonington commented
This looks good to me, though the only concern I have is the yarn file and the dependencies. The pushed conflict is from upgrading some dependencies to avoid certain vulnerabilities. A yarn upgrade and yarn install will likely need to be ran after resolving the merge conflicts.

2024-10-24 21:47 UTC, mdorford commented
> This looks good to me, though the only concern I have is the yarn file and the dependencies. The pushed conflict is from upgrading some dependencies to avoid certain vulnerabilities. A yarn upgrade and yarn install will likely need to be ran after resolving the merge conflicts.

Fixed.  Merged the yarn.lock file so it is using the yarn.lock file from your update.

2024-10-24 21:49 UTC, pmonington approved these changes

2025-03-18 16:44 UTC, payneBrandon commented on src/App.tsx
> +        ? "https://sdx-service.trihydro.com"
suggestion: do you think we should default to beta site now that we've added in some deposit functionality?

2025-03-18 16:58 UTC, payneBrandon commented on src/App.tsx
> +    const urlMissing = !process.env.REACT_APP_URL;
suggestion: let's add this override url to the README as well. Might be good to add a sample.env with possible value.

2025-03-18 18:48 UTC, payneBrandon requested changes
Just a couple small questions. Looks great!

2025-03-18 20:46 UTC, mdorford commented on src/App.tsx
> +        ? "https://sdx-service.trihydro.com"
Done.  Although a person still needs the proper AspNetRoles role and an Organization to be allowed to deposit.  If a person does not have permission to deposit, they get this popup:
_To have the DepositMulti function enabled, you will need to contact Trihydro._

2025-03-18 21:11 UTC, mdorford commented on src/App.tsx
> +    const urlMissing = !process.env.REACT_APP_URL;
Done.

2025-03-18 21:29 UTC, payneBrandon approved these changes
lgtm!

2025-03-18 21:29 UTC, merged